#!/usr/bin/env bash
# Function to display subdomain information
display_subdomain_info() {
    local domain=$1
    local subdomain=$2

    # Performing DNS lookup using awk
    dig_output=$(dig $subdomain.$domain | awk '/ANSWER SECTION:/ { getline; print }')

    # Extract record type and destination from the dig output
    record_type=$(echo $dig_output | awk '{print $4}')
    destination=$(echo $dig_output | awk '{print $5}')

    # Display the subdomain
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    # Displaying the information for default subdomains
    display_subdomain_info $domain www
    display_subdomain_info $domain lb-01
    display_subdomain_info $domain web-01
    display_subdomain_info $domain web-02
else
    # Display information for the specified subdomain
    display_subdomain_info $domain $subdomain
fi
